version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jasmine",
    "browser",
    "nodejs",
    "jquery",
    "jest"
  ]
  plugins = ["angular"]
  style_guide = "standard"
  dialect = "typescript"
